<?php

namespace ContainerM4W7xwx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2lrQJM3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2lrQJM3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2lrQJM3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailerInterface' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'mailerInterface' => '?',
            'managerRegistry' => '?',
        ]);
    }
}
