<?php

namespace ContainerM4W7xwx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LogGoDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.logGoD_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.logGoD_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'user' => ['privates', '.errored..service_locator.logGoD_.App\\Entity\\Newsletters\\Users', NULL, 'Cannot autowire service ".service_locator.logGoD_": it references class "App\\Entity\\Newsletters\\Users" but no such service exists.'],
        ], [
            'managerRegistry' => '?',
            'user' => 'App\\Entity\\Newsletters\\Users',
        ]);
    }
}
