<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMFRmZs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMFRmZs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKMFRmZs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKMFRmZs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKMFRmZs\App_KernelDevDebugContainer([
    'container.build_hash' => 'KMFRmZs',
    'container.build_id' => '7d6d89fe',
    'container.build_time' => 1664455955,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMFRmZs');
