<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX6mzHt5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX6mzHt5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX6mzHt5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX6mzHt5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX6mzHt5\App_KernelDevDebugContainer([
    'container.build_hash' => 'X6mzHt5',
    'container.build_id' => '979a5adc',
    'container.build_time' => 1664371441,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX6mzHt5');
