<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYO6xhpx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYO6xhpx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYO6xhpx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYO6xhpx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYO6xhpx\App_KernelDevDebugContainer([
    'container.build_hash' => 'YO6xhpx',
    'container.build_id' => '28fe272c',
    'container.build_time' => 1664290792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYO6xhpx');
